### ISSUE TITLE
000013

### ISSUE THREAD

**Issue by Skeeva007** [VPRL/Virginia-Philosophy-Reality-Lab#34]
# Beta Testing #

* There are two active paths you can take to help us beta test this experience. 
* We will give you 2 unique codes to test both paths, one will be an even number and one will be an odd number.
  * If you enter in an even number you will be participating in the **switch** study.
  * If you enter in an odd number you will be participating in the **push** study. 
* Please attempt to answer the following questions to the best of your ability.

## Equipment Details ##
>Please select one:

- [ ] Oculus Quest 1
- [X ] Oculus Quest 2
- [ ] Oculus Qust Rift S
- [ ] Oculus OG 🕶️

## Scenario Details ###
>Please describe the scenario as you experienced it
There were workers on the track, the only way to save the 5 was to push the 1 off onto the tracks

## Beta Test Version ###
>This should be [0.1.0-beta](https://github.com/vmasc-odu/Virginia-Philosophy-Reality-Lab/releases/tag/0.1.0-beta)

### Estimated Time ###
> Please provide the rough time you started the experience and use time zones, e.g. *12:30am EST May 4, 2021*
3:20pm MST 5/11/21

### Qualtrics Code ###

> Please enter the 6 digit survey code you used here e.g. '123456'
000013

### Training Decision on Pulling the Switch ###
>Please select one:

- [x ] Followed Directions: sent the train towards the bridge 🌉
- [ ] You Caused Trouble: sent the train towards the curve 

### Training Decision on Stopping the Train with the Barrel ###
>Please select one:

- [ x] Followed Directions: pushed the barrel to stop the train
- [ ] You Caused Trouble: did not push the barrel and the system took over

### Moral Control Decision ###
>Please select one:

*For EVEN survey code (Switch Study)*
- [ ] You sent the train away from the people
- [ ] You did nothing and the five people died 🤯
- [ ] You did nothing and the five people lived 🐛

*For ODD survey code (Push Study)*
- [ ] You stopped the train with a Barrel
- [ ] You did nothing and the five people died 🤯
- [ ] You did nothing and the five people lived 🐛

### Test Study Decision ###
>Please select one:

*For EVEN survey code (Switch Study)*
- [ ] You pulled the switch, killed 1, saved 5
- [ ] You did *not* pull the switch, killed 5

*For ODD survey code (Push Study)*
- [ x] You pushed a person, killed 1, saved 5
- [ ] You did *not* push a person, killed 5

### System Crash ##
- [ ] Did you Encounter a Crash? No
> Please explain what happened, do you remember if you were interacting with anything? Do you remember about where you were in the experience?
> If you want to be really helpful 🥰 and you think you can recreate the crash and know how to run adb logcat please dump us the file here! 
> If not no worries, we still 🖤 you.

### Additional Comments & Details ###
>Any other feedback? Notes? Suggestions? Little things you noticed? Anything?! Please and thank you!😺

The controls did not work as expected. 
It took multiple presses of the CCTV buttons to change the camera.
I found it difficulty to push and pull the lever. When pushing the lever sometimes it would come back
I also pushed the barrel onto the tracks but it didn't stop the train. The train went through anyway

**Comment by JShull** [comment]
Thanks so much @Skeeva007 for testing out the application! 

I have your raw data cleaned up to remove some unique information and will be building some additional tests from your contribution/submission. 

Once we get some of that testing data parsed I am planning on releasing a simple web viewer app that will let you replay your motion and event data. This is probably a few weeks off.

Coming up within by next week we are planning on releasing the raw data back to the users and that will be done here with me closing out the issue. Right now this is looking like May 17th, 2021.

Thanks again for the contribution - and that smooth radio/podcast voice that you have comes through just as wonderful through the Quest 2 💯

**Comment by Skeeva007** [comment]
Haha! 😂
Sounds good! Let me know if i can help in any way. I'm always here!

**Comment by Kisselphil** [comment]
Yes, thanks very much @Skeeva007, we really appreciate you taking the time to playtest this for us!

**Comment by JShull** [comment]
@Skeeva007 just updating you as you can now access the data we pulled back from you [here](https://github.com/vmasc-odu/Virginia-Philosophy-Reality-Lab/tree/main/TestData/000013)
