### ISSUE TITLE
User Flow in the Office

### ISSUE THREAD

**Issue by JShull** [VPRL/Virginia-Philosophy-Reality-Lab#37]
Great Feedback from 
#35
# Adjustments Needed

## Office
>Upon entering the office we need to address the following items in one cc/audio blurb
>Office Introduction Narration/CC and Audio Updates
  - [x] How you navigate/Teleport
  - [x] Modify information about the menu to include "additional settings": menu position
  - [x] Introduction to seat/stand = remove and combine
  - [x] Check out the computer before you're ready
- [x] UI Changes and removal of old audio blurb/narration timeline
  - [x] Touch screen to go through these options up front and then grant you the menu upon finishing that (no audio/cc cues needed) text on screen
 
## Control Booth
>Record all new voice/cc for the following items listed below (switch / bridge / curve )

- [x] Curve = Spur Track
- [x] Bridge = Main Track
- [x] Switch System = Control Booth
  - [x] Introduction to tower =remove and combine with CCTV training
  - [x] Entire "Switch" training needs new narrative and new CC
  - [x] Entire FirstTrainSuccess new narration and cc
  - [x] Entire FirstTrainFailure new narration using Spur and main line and cc
  - [x] Entire Water Barrel_00 narrator needs to be replaced with removal of switch and replace with 'control booth'
  - [x] Entire Water Barrel_01 narrator needs to be replaced with removal of switch
 
## Misc Fixes
- [x] Entire CC TV training gets gutted and rerouted for the state machine
- [x] After Moral Control, non-barrel pushed, we need to 'eject' the barrel without activating the other state (activate dummy barrel protocol)

**Comment by JShull** [comment]
Going to try and record all the narration early in the AM prior to some of the on-site work - for the most part the entire first half of the recordings and their cc have to be redone mainly because the office scenarios are changing and then I must use the word "switch" a hundred times 😄 but I think I should have all of those wrapped by end of day Wednesday 6-9

**Comment by Kisselphil** [comment]
After discussion at today's meeting, we confirmed that we would continue to refer to the "switch system", since you are switching tracks.
In place of language to "reach and pull the switch", we will say "press the button to switch to the spur" or "press the button to switch to the main track".
"Bridge"--> Main Track
"Curve"--> Spur

Let me know if there is other language language problems that we bump into.

**Comment by JShull** [comment]
Barrel now has a dummy type. When we need to clear the right barrel on moral control spur failure we activate the automatic launcher and equally make the barrel a dummy - upon collision nothing happens and we just destroy the barrel.
