### ISSUE TITLE
000006

### ISSUE THREAD

**Issue by thetrashy1** [VPRL/Virginia-Philosophy-Reality-Lab#39]
# Beta Testing #

* There are two active paths you can take to help us beta test this experience. 
* We will give you 2 unique codes to test both paths, one will be an even number and one will be an odd number.
  * If you enter in an even number you will be participating in the **switch** study.
  * If you enter in an odd number you will be participating in the **push** study. 
* Please attempt to answer the following questions to the best of your ability.

## Equipment Details ##
>Please select one:

- [x ] Oculus Quest 1
- [ ] Oculus Quest 2
- [ ] Oculus Qust Rift S
- [ ] Oculus OG 🕶️

## Scenario Details ###
>Please describe the scenario as you experienced it
I was introduced to the controls via a training scenario, then given the opportunity to decide which track the train runs on in 2 situations. 1. When there are workers on the bridge and none on the tower track. 2. When there are 5 workers on the bridge and 1 on the tower track.

## Beta Test Version ###
>This should be [0.1.0-beta](https://github.com/vmasc-odu/Virginia-Philosophy-Reality-Lab/releases/tag/0.1.0-beta)

### Estimated Time ###
> Please provide the rough time you started the experience and use time zones, e.g. *12:30am EST May 4, 2021*
2:30pm EST May 14 2021

### Qualtrics Code ###

> Please enter the 6 digit survey code you used here e.g. '123456'
000006

### Training Decision on Pulling the Switch ###
>Please select one:

- [ ] Followed Directions: sent the train towards the bridge 🌉
- [ x] You Caused Trouble: sent the train towards the curve 

### Training Decision on Stopping the Train with the Barrel ###
>Please select one:

- [ x] Followed Directions: pushed the barrel to stop the train
- [ ] You Caused Trouble: did not push the barrel and the system took over

### Moral Control Decision ###
>Please select one:

*For EVEN survey code (Switch Study)*
- [x ] You sent the train away from the people
- [ ] You did nothing and the five people died 🤯
- [ ] You did nothing and the five people lived 🐛

*For ODD survey code (Push Study)*
- [ ] You stopped the train with a Barrel
- [ ] You did nothing and the five people died 🤯
- [ ] You did nothing and the five people lived 🐛

### Test Study Decision ###
>Please select one:

*For EVEN survey code (Switch Study)*
- [ x] You pulled the switch, killed 1, saved 5
- [ ] You did *not* pull the switch, killed 5

*For ODD survey code (Push Study)*
- [ ] You pushed a person, killed 1, saved 5
- [ ] You did *not* push a person, killed 5

### System Crash ##
- [ ] Did you Encounter a Crash?
> Please explain what happened, do you remember if you were interacting with anything? Do you remember about where you were in the experience?
> If you want to be really helpful 🥰 and you think you can recreate the crash and know how to run adb logcat please dump us the file here! 
> If not no worries, we still 🖤 you.

### Additional Comments & Details ###
>Any other feedback? Notes? Suggestions? Little things you noticed? Anything?! Please and thank you!😺

I was more familiar with the setup and better oriented with the space on my second runthrough, so I focussed more on the control options. I still had a lot of trouble manipulating the track switch handle. It was unresponsive and didn't seem to always register my interactions.

I also noticed that while it seems like the color coding is meant to convey that blue is operable and red is locked/inoperable, the 'hover' state of interaction with a blue object is red. This feels sort of counterproductive to the establishment of the blue/red distinction. I wonder if it would be clearer to use a more standard pattern of GREEN for operable and red for inoperable, with blue as the hover state? Or some other way of indicating selection/hover if you don't want to introduce a third color (probably wise).

I also wonder about the system power knobs (I think there are 5?). It seems that whether there is power and the system is active is a binary state (off or on, defined by red or blue). So having there also be 5 knobs as part of that UI piece seems extraneous/arbitrary. I saw it as maybe some kind of meter that would fill, like there might be 5 levels of power? Would it make sense to just reduce this to one indicator? Or just a display that says 'active' and 'locked' or something to that effect.
Similarly, I was a little confused by the third knob on the UI of the lever for track switching. It seems there are 2 binary states (bridge or curve) so why not just have 2 knob-things? I was wondering if there was some kind of middle setting in between the 2 options.

Sorry if I'm not explaining myself well in this message, I'd be happy to provide verbal feedback to Dr. Kissel next time I see him!

**Comment by JShull** [comment]
Thanks @thetrashy1 for the updates - working on pulling back your data for this run and should have it up by end of the week.

**Comment by JShull** [comment]
Hey @thetrashy1 thanks for working with us - following up with your data.

You can now access the data that we pulled back from this first event [here](https://github.com/vmasc-odu/Virginia-Philosophy-Reality-Lab/tree/main/TestData/000006)
