### ISSUE TITLE
Changes to Trolley Problem Based on Beta Feedback

### ISSUE THREAD

**Issue by Kisselphil** [VPRL/Virginia-Philosophy-Reality-Lab#40]
## Office Sequence ##
- [ ] See Issue #37 

## Track Changes ##
- [x] Adjust curve to run parallel to bridge (both tracks should go over chasm)
~- [ ] Remove fencing on bridges~
- [x] Move workers closer to control tower

## Control Tower Changes ##
- [x] Remove switch, replace with buttons
- [x] Remove cameras
- [x] Change status lights to "Active/ Inactive" message
- [x] Rotate tower so barrels/ pushed man will land on track after adjustments to curve (See "Track Changes" below)

## Animations ##
- [x] Work animation loops
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- [ ] Man on laptop
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-  [ ] Man hammering
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- [ ] Welding
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- [ ] Other?
- [ ] Getting back into truck animation?

## Sound Design ##
- [x] Ambient noise while in control tower (Ex. https://assetstore.unity.com/packages/audio/ambient/nature/cicada-sound-pack-vol-01-33453 or https://assetstore.unity.com/packages/audio/ambient/nature/organic-nature-38394)

### Additional Comments & Details ###
- We discussed white boxing the track changes and control tower changes first to make sure that it fits what we're hoping for.  I think we should try that first, as we may choose to move the tower in between the tracks in the long run.
- Please add any additional changes we discussed that may have been left off this initial list.

**Comment by JShull** [comment]
I pulled BaTo off the animations because I couldn't give him enough detail requirements that would make sense for his time and/or effort so before I waste his time I need to spend a few hours providing more details to him on the current state of when they jump out of the truck as well as where/how they get back in.

**Comment by Kisselphil** [comment]
We decided to go with all male bodies for the study, to avoid female/ male moral decision making biases.

**Comment by Kisselphil** [comment]
Additional Issue: The GitHub page that the app links to upon completion needs to be updated to the new page.  The new link is www.vprl.org

**Comment by JShull** [comment]
Ambient sounds added.
GitHub page link fixed
Not dealing with 'getting back in the truck' via BaTo and just going to reverse my existing scripts to do it automatically without taxing on other efforts.
Animations are in the project not in the scene yet - going to kill this issue
