### ISSUE TITLE
Moral Control Audio Worker Bug

### ISSUE THREAD

**Issue by Kisselphil** [VPRL/Virginia-Philosophy-Reality-Lab#49]
**Describe the problem**
After the workers in the moral control drove away, their construction sounds continued throughout the rest of the experience (including during the exit survey).

**To Reproduce**
This occurred during the moral control for run 666006.  Perhaps worth noting, during the barrel training on this run I pushed the barrel but too late to stop the train.

**Oculus Question Information (please complete the following information):**
 - Device: Quest 2
 - Software Version: 30.1.0.61.350.300158191

**Additional context**
Other sounds continued to work normally, including worker sounds for the experiment portion.

**Comment by JShull** [comment]
This is hilarious - easy fix forgot to kill the gameobject so they are still alive but probably somewhere falling through space and time.

**Comment by JShull** [comment]
- This error primarily occurs in two sort of outcomes
  - We have the truck drive off and leaves the people (study related - and you save them)
    - Fix: All vehicles at the end before we start audio narration are polled and we fully make sure to remove the people 
  - Moral control failure
    - Fix: All moral control trucks remove people at end of their time
