### ISSUE TITLE
Mechanical Sound for Board Unlocking

### ISSUE THREAD

**Issue by Kisselphil** [VPRL/Virginia-Philosophy-Reality-Lab#50]
**Describe the Adjustment**
I think we need to add one more sound back in.  When the user is first introduced to the control board, the voice says "that sound is the sound of the board unlocking" (or something like that).  But there is no mechanical sound accompanying the narration.

**Things to Consider**
Guideline of information needed:
1. This occurs in the control booth
2. It involves the addition of a sound when the control board/ switch unlocks
3. This is not a time based adjustment
4. This is not a bug

**Comment by JShull** [comment]
This is related to #46 - once I update the audio manager this sound bug will be fixed
